version: "3.9"

services:
  api:
    container_name: api-prueba
    image: "nginx:1.25.2-alpine"
    restart: always
    working_dir: /app
    links:
      - php-fpm
    volumes:
      - "./backend/.:/app"
      - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8099:80"

  php-fpm:
    container_name: php-fpm-prueba
    build: docker/php-fpm
    restart: always
    working_dir: /app
    links:
      - db
    volumes:
      - "./backend/.:/app"
      - "./docker/php-fpm/php-overrides.ini:/usr/local/etc/php/conf.d/php-overrides.ini"
    environment:
      XDEBUG_MODE: "debug"
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
      COMPOSER_ALLOW_SUPERUSER: 1

  db:
    image: "mariadb:11.1.2"
    restart: always
    working_dir: /app
    volumes:
        - "./backend/.:/app"
        - "./docker/mariadb/data:/var/lib/mysql"
        - "./docker/mariadb/logs:/var/log/mysql"
        - "./docker/mariadb/conf:/etc/mysql"
    environment:
        MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
        MARIADB_DATABASE: "${MARIADB_DATABASE}"
        MARIADB_USER: "${MARIADB_USER}"
        MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
    ports:
        - "3306:3306"

  redis:
    container_name: redis-prueba
    image: "redis:7.2.0-alpine"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - datacacheprueba:/data
  
  frontend:
    container_name: nginx-prueba-frontend
    image: "nginx:1.25.2-alpine"
    restart: always
    working_dir: /app
    volumes:
      - "./frontend/.:/app"
      - "./docker/nginx/nginx_frontend.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8090:80"

volumes:
  datacacheprueba:
